### PR TITLE
Update to Composer 1.1.0

### PR DESCRIPTION
**Pull request by RobLoach**
Used the update script, it worked well! Mind reviewing and then merging??? :+1:

### CODE REVIEW

**Comment by sylus** [comment]
Looks good to me but I noticed we don't have a corresponding update in the makefile to test the added folder with Travis.

Is this something the update script should be handling? Something like this is done for the travis file itself when the logic is all contained in that file:

https://github.com/docker-library/postgres/blob/master/update.sh#L15

**Comment by RobLoach** [comment]
Good catch. For now, I'll add it manually in the PR. We could follow up with fixing update.sh more afterwards.

**Comment by sylus** [comment]
I think just need the alpine 1.1.0 test added to the makefile then good to go. :)

**Comment by RobLoach** [comment]
We could wrap #74 into it.

**Pull request merged**
