### PR TITLE
Add wget

### PR DESCRIPTION
**Pull request by RobLoach**
Fixes https://github.com/kalabox/kalabox/issues/1284

Surprised it wasn't there from the start.

### CODE REVIEW

**Comment by pirog** [comment]
@RobLoach yeah also surprised. The Docker Gods are fickle. 

Tests are broken on installing composer but restarted to see if it temporary internet woes.

**Comment by pirog** [comment]
Yeah @RobLoach, builds are failing on composer install

```bash
Step 11 : RUN php -r "readfile('https://getcomposer.org/installer');" > /tmp/composer-setup.php   && php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== '${COMPOSER_INSTALLER_SHA384}') { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }"
 ---> Running in df14c354aa7c
Invalid installer
The command '/bin/sh -c php -r "readfile('https://getcomposer.org/installer');" > /tmp/composer-setup.php   && php -r "if (hash('SHA384', file_get_contents('/tmp/composer-setup.php')) !== '${COMPOSER_INSTALLER_SHA384}') { unlink('/tmp/composer-setup.php'); echo 'Invalid installer' . PHP_EOL; exit(1); }"' returned a non-zero code: 1
make: *** [build] Error 1
```

**Comment by pirog** [comment]
@RobLoach k, just had to update the install script SHASHA and i think we will be back in bizniss

See: https://www.getyarn.io/yarn-clip/a93d2852-0d86-4fb9-a86d-cfef174f06dd

**Comment by SydOps** [comment]
@pirog & @RobLoach 

How did you get `COMPOSER_INSTALLER_SHA384`, I have same issue when build the image, seems I need update the SHA key, but how to do that?

**Comment by RobLoach** [comment]
The hash is from https://getcomposer.org/download/

**Pull request merged**
