### PR TITLE
Fix #113: use the "community" repo for php7-pear in Alpine-based image

### LINKED ISSUE #113: PEAR tmp fix breaks the builds of Alpine-based images
https://github.com/RobLoach/docker-composer/blob/3ae582213877cb13e576160b42c004ff536da88e/base/alpine/Dockerfile#L32-L35

Example of a failed build: #112

### PR DESCRIPTION
**Pull request by EvgenyOrekhov**

### CODE REVIEW

**Comment by BastienM** [comment]
Hi,

Already patched the issue last week, see #110 ;)

**Comment by EvgenyOrekhov** [comment]
@BastienM indeed. I can see now that your build failed because of `500 Internal Server Error`. You should've force-pushed your commits to trigger a new CI build and make your PR green.

**Comment by BastienM** [comment]
Considering the 500, I didn't really thought that it would matter.
It should be ok by now.

Now let's hope the team will merge either one the patch soon :)

**Comment by EvgenyOrekhov** [comment]
@BastienM some maintainers might not even look at a PR that has failed checks, they will wait until a contributor makes it green.

**Comment by RobLoach** [comment]
Thanks a lot! I see it's `@edge` instead of `@community`. That doesn't matter so much, correct? Other then that I think this can be closed.

Thanks for the help, @EvgenyOrekhov, and the ping in re-running tests. Well done, you two!

**Comment by EvgenyOrekhov** [comment]
@RobLoach `@edge` is just a user-defined alias for the repo link, it doesn't really matter.
You're welcome! I think you can close #106 and #113 now =)

**Comment by BastienM** [comment]
@RobLoach :  as @EvgenyOrekhov said, it just a arbitrary tag.

The package still is in the edge repositories but has moved from testing to community staging :)

**Pull request closed without merging**
