### PR TITLE
Use the new installer script per https://getcomposer.org/download/.

### PR DESCRIPTION
**Pull request by echernyavskiy**

### CODE REVIEW

**Comment by RobLoach** [comment]
Looks great :+1: . Thanks for pushing this forwards.

**Comment by echernyavskiy** [comment]
Sure thing. Please also see my comment on Docker Hub - looks like some tags have not been built, including the long-awaited `1.0.0`:

    Tags 1.0.0-beta2 and 1.0.0 while listed in the README are currently not available on Docker Hub.

**Comment by RobLoach** [comment]
https://hub.docker.com/r/composer/composer/tags/ Should be up... beta2 is still buildling I believe.

**Comment by echernyavskiy** [comment]
Awesome, much appreciated

**Pull request merged**
