### PR TITLE
Add deprecation notice

### PR DESCRIPTION
**Pull request by RobLoach**

### CODE REVIEW

**Review by pmoust — APPROVED** [review]

**Comment by RobLoach** [comment]
Thanks!

**Comment by caugner** [comment]
@RobLoach Docker Hub [didn't pick the deprecation notice up yet](https://hub.docker.com/r/composer/composer/). Could it be that you still need to manually push the changes to the Hub?

**Comment by RobLoach** [comment]
Added it manually

**Comment by RobLoach** [comment]
Thanks!

**Pull request merged**
