### PR TITLE
Bump composer 1.1 to latest version

### PR DESCRIPTION
**Pull request by zoidbergwill**
https://github.com/composer/composer/blob/master/CHANGELOG.md#112---2016-05-31

### CODE REVIEW

**Comment by RobLoach** [comment]
Looks like https://github.com/RobLoach/docker-composer/issues/81 is blocking.

**Comment by sylus** [comment]
#81 is now fixed, I had to resort grabbing php7-pear from testing. Hopefully in next alpine release will be part of stable.

**Comment by sylus** [comment]
All of the other versions (alpine, php5-alpine) should have the 1.1.0 to 1.1.2 as well. You can simply run `./update.sh` or just manually edit the other two entries before this can be merged.

**Comment by sylus** [comment]
Closing this out in favor of #84

**Pull request closed without merging**
