### PR TITLE
Use Alpine Linux for a smaller image size

### PR DESCRIPTION
**Pull request by sjparkinson**
This is simply an unconflicted version of PR #19.

I've also added the `php-cli` package explicitly and added in `php-pdo` and `php-dom` to help with platform requirement checks.

The list of available php packages is here: https://pkgs.alpinelinux.org/packages?name=php%25&repo=main&arch=x86_64&maintainer=all

Here's the supported extensions:

```bash
$ docker run --rm -t composer/composer show --platform
composer-plugin-api 1.0.0    The Composer Plugin API
ext-bz2             0        The bz2 PHP extension
ext-date            5.6.13   The date PHP extension
ext-dom             20031129 The dom PHP extension
ext-ereg            0        The ereg PHP extension
ext-fileinfo        1.0.5    The fileinfo PHP extension
ext-filter          0.11.0   The filter PHP extension
ext-gd              0        The gd PHP extension
ext-hash            1.0      The hash PHP extension
ext-json            1.2.1    The json PHP extension
ext-libxml          0        The libxml PHP extension
ext-mbstring        0        The mbstring PHP extension
ext-mcrypt          0        The mcrypt PHP extension
ext-mysqlnd         0        The mysqlnd PHP extension
ext-openssl         0        The openssl PHP extension
ext-pcre            0        The pcre PHP extension
ext-PDO             1.0.4dev The PDO PHP extension
ext-Phar            2.0.2    The Phar PHP extension
ext-readline        5.6.13   The readline PHP extension
ext-Reflection      0        The Reflection PHP extension
ext-session         0        The session PHP extension
ext-SimpleXML       0.1      The SimpleXML PHP extension
ext-SPL             0.2      The SPL PHP extension
ext-tokenizer       0.1      The tokenizer PHP extension
ext-xml             0        The xml PHP extension
ext-xmlwriter       0.1      The xmlwriter PHP extension
ext-zip             1.12.5   The zip PHP extension
lib-libxml          2.9.2    The libxml PHP library
lib-openssl         1.0.1.16 The openssl PHP library
lib-pcre            8.36     The pcre PHP library
php                 5.6.13   The PHP interpreter
php-64bit           5.6.13   The PHP interpreter (64bit)
```

### CODE REVIEW

**Comment by RobLoach** [comment]
This is looking great! Are there any other PHP extensions that we'd want? I've seen people want `imagemagik`.

Anything else you can think of?

**Comment by sjparkinson** [comment]
I had a quick browse of the top packagist packages, the main one with extension requirements is phpunit which is now covered after adding `pdo-dom` on top of the rest.

I'll have a look into the `imagemagik`, but it's not available as an alpine package. That might be a better one to suggest using `--ignore-platform-reqs`.

**Comment by sjparkinson** [comment]
> I'll have a look into the imagemagik, but it's not available as an alpine package. That might be a better one to suggest using --ignore-platform-reqs.

So I don't think it's worth adding until there's a package available. It'd either add complexity to the base run step or an extra layer which defeats the point of keeping the image small.

There's a request for the package to be added to alpine here: http://bugs.alpinelinux.org/issues/4277

**Comment by sjparkinson** [comment]
@RobLoach added on a few updates, any chance of a merge?

**Comment by sjparkinson** [comment]
Closing this as we've made the [graze/composer](https://hub.docker.com/r/graze/composer/) image instead, and there's still #19.

**Pull request closed without merging**
